run:
	python3 paragraph_sender.py
dcup-light:
	cd .. && make dcup-light
run-ktor:
	cd ../whiskers-ktor && make run
cat-sayings-run:
	curl -i http://localhost:8080/
cat-sayings-list:
	curl -i http://localhost:8080/cat/sayings/