services:
  whiskers-ktor-no-db:
    build:
      context: ./whiskers-ktor-no-db/.
    networks:
      - whiskers-network
    expose:
      - 8080
    depends_on:
      whiskers-db:
        condition: service_healthy
