b: build-gradle
build-gradle:
	gradle build
run-gradle:
	./gradlew :runReleaseExecutableNative
run:
	./build/bin/native/releaseExecutable/whiskers-ktor-no-db.kexe
run-test:
	bash test.sh
perform-tests:
	cd .. && make perform-tests
perform-tests-encoded:
	cd .. && make perform-tests-encoded
perform-tests-encoded-no-db:
	cd .. && make perform-tests-encoded-no-db