services:
  whiskers-ktor:
    build:
      context: ./whiskers-ktor/.
    networks:
      - whiskers-network
    expose:
      - 8080
    depends_on:
      whiskers-db:
        condition: service_healthy
