name: Build on PR

on:
  pull_request:
    branches: [ main ]
  push:
    branches:
      - "!main"

jobs:
  build-test-good-feel:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project sources
        uses: actions/checkout@v4
      - uses: graalvm/setup-graalvm@!
        with:
          version: 'latest'
          java-version: '21'
          components: 'native-image'
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v3

      - name: Build Gradle
        run: make build-gradle-good-feel

  build-test-plus:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project sources
        uses: actions/checkout@v4
      - uses: graalvm/setup-graalvm@!
        with:
          version: 'latest'
          java-version: '21'
          components: 'native-image'
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v3

      - name: Build Gradle
        run: make build-gradle-plus

  build-test-ktor-no-db:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project sources
        uses: actions/checkout@v4
      - uses: graalvm/setup-graalvm@!
        with:
          version: 'latest'
          java-version: '21'
          components: 'native-image'
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v3

      - name: Setup Gradle 8.10.1
        run: export GRADLE_OPTS="-Xmx2048m -Dorg.gradle.jvmargs='-Xmx2048m -XX:MaxPermSize=2048m'"

      - name: Build Gradle
        run: make build-gradle-ktor-no-db

  build-test-ktor:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project sources
        uses: actions/checkout@v4
      - uses: graalvm/setup-graalvm@!
        with:
          version: 'latest'
          java-version: '21'
          components: 'native-image'
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v3

      - name: Linux libraries
        run: sudo apt install libreadline-dev &&
          sudo apt-get install libpq-dev &&
          sudo apt install bison &&
          sudo apt install flex

      - name: Setup Binaries
        run: make setup-binaries

      - name: Setup Gradle 8.10.1
        run: export GRADLE_OPTS="-Xmx2048m -Dorg.gradle.jvmargs='-Xmx2048m -XX:MaxPermSize=2048m'"

      - name: Install Kotlin Native
        run: make install-kotlin-native-linux-ktor

      - name: Install Postgres
        run:  cd whiskers-ktor/postgresql/postgres-master && ./configure && make all

      - name: Build Gradle
        run: make build-gradle-ktor

  build-graalvm-exec-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: gradle/gradle-build-action@v3
      - uses: graalvm/setup-graalvm@!
        with:
          version: 'latest'
          java-version: '21'
          components: 'native-image'
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Gradle GraalVM
        run: make build-gradle-exec-graalvm

  build-graalvm-cloud-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: gradle/gradle-build-action@v3
      - uses: graalvm/setup-graalvm@!
        with:
          version: 'latest'
          java-version: '21'
          components: 'native-image'
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Gradle GraalVM
        run: make build-gradle-cloud-graalvm

  build-whiskers-red-cat:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project sources
        uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'adopt'
          java-version: '21'

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v3

      - name: Setup Binaries
        run: make setup-binaries

      - name: Install Kotlin Native
        run: make install-kotlin-native-linux-rc

      - name: Build Gradle Red Cat
        run: make build-gradle-redcat

  build-whiskers-red-cat-db:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project sources
        uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'adopt'
          java-version: '21'

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v3

      - name: Linux libraries
        run: sudo apt install libreadline-dev &&
          sudo apt-get install libpq-dev &&
          sudo apt install bison &&
          sudo apt install flex

      - name: Setup Binaries
        run: make setup-binaries

      - name: Install Kotlin Native
        run: make install-kotlin-native-linux-rcdb

      - name: Install Postgres
        run:  cd whiskers-red-cat-db/postgres-master && ./configure && make all

      - name: Build Gradle Red Cat
        run: make build-gradle-redcat-db

  build-runners:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: gradle/gradle-build-action@v3
      - uses: graalvm/setup-graalvm@!
        with:
          version: 'latest'
          java-version: '21'
          components: 'native-image'
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Gradle Runners
        run: make build-runners
