name: e2e-whiskers

on: push

jobs:
  e2e-electron:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'

#      - name: Start Docker
#        run: make dcup-full-isolated-action
#
#      - name: Run Cypress
#        run: make cypress-electron

  e2e-chrome:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'

#      - name: Start Docker
#        run: make dcup-full-isolated-action
#
#      - name: Run Cypress
#        run: make cypress-chrome

  e2e-firefox:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'

#      - name: Start Docker
#        run: make dcup-full-isolated-action
#
#      - name: Run Cypress
#        run: make cypress-firefox
#        continue-on-error: true

  e2e-edge:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'

#      - name: Start Docker
#        run: make dcup-full-isolated-action
#
#      - name: Run Cypress
#        run: make cypress-edge
